# Generated by Django 6.0.1 on 2026-04-09 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='When the session began.', verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the session ended (set when completed).', null=True, verbose_name='end time')),
                ('duration', models.IntegerField(blank=True, help_text='Session length in seconds (set when completed).', null=True, verbose_name='duration')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', help_text='Whether the session is active, paused, or completed.', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(help_text='The user this session belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='flow_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
