# Generated by Django 6.0.1 on 2026-04-09 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The calendar day this row summarizes.', verbose_name='date')),
                ('total_focus_time', models.IntegerField(default=0, help_text='Total focus time in seconds (sum of completed sessions that day).', verbose_name='total focus time')),
                ('circular_progress', models.FloatField(default=0.0, help_text='Percentage of daily goal achieved (0–100); updated by views later.', verbose_name='circular progress')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sessions', models.ManyToManyField(blank=True, help_text='Completed sessions counted toward this day (optional link for queries).', related_name='daily_statistics', to='core.session', verbose_name='sessions')),
                ('user', models.ForeignKey(help_text='The user this daily aggregate belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='daily_statistics', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'daily statistic',
                'verbose_name_plural': 'daily statistics',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
