# Generated by Django 6.0.3 on 2026-04-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_daily_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='focus_quality',
            field=models.PositiveSmallIntegerField(blank=True, help_text='User rating indicating session quality (e.g. 1-5).', null=True, verbose_name='focus quality'),
        ),
    ]
