# Generated by Django 6.0.1 on 2026-04-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_session_focus_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='target_duration',
            field=models.PositiveIntegerField(default=1500, help_text="The user's chosen session goal in seconds (e.g. 1500 for 25 min).", verbose_name='target duration'),
        ),
    ]
