# Generated by Django 6.0.1 on 2026-04-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_target_duration_to_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystatistic',
            name='daily_goal',
            field=models.PositiveIntegerField(default=120, help_text="The user's focus-time goal for this day, in minutes.", verbose_name='daily goal (minutes)'),
        ),
    ]
