# Generated by Django 6.0.1 on 2026-04-19 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dailystatistic_daily_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream_goal', models.CharField(blank=True, default='', help_text="The user's long-term dream or career aspiration (e.g. 'IAS', 'Software Engineer').", max_length=255, verbose_name='dream goal')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this profile record was first created.', verbose_name='created at')),
                ('user', models.OneToOneField(help_text='The user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
    ]
