# Generated by Django 6.0.1 on 2026-05-23 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_todoitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'todo item', 'verbose_name_plural': 'todo items'},
        ),
        migrations.RemoveIndex(
            model_name='todoitem',
            name='core_todoit_user_id_700c07_idx',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='order',
            field=models.IntegerField(default=0, help_text='Used for drag-and-drop sorting.'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='text',
            field=models.CharField(default='', help_text='The text of the to-do item.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether the task is checked off.'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='user',
            field=models.ForeignKey(help_text='The user this task belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='title',
        ),
    ]
