# Generated by Django 6.0.1 on 2026-05-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_todoitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(blank=True, default='', help_text="Eisenhower Matrix priority (e.g., 'Urgent & Important').", max_length=50),
        ),
    ]
