# Generated by Django 6.0.1 on 2026-05-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_todoitem_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(blank=True, default='Not Urgent & Not Important', max_length=50, null=True),
        ),
    ]
